#include "the.h"
#include <string.h>
//#include <algorithm>
//==============================================================================
//==============================================================================
/*void TheString::removeComment(string& str) {
	removeLeadingWhiteSpace(str);
	if (str[0]==COMMENT_CHAR1 || str[0]==COMMENT_CHAR2) {
		str="";
		return;
	}
	????
	removeTrailingWhiteSpace(str);
}
*/
