'''
    quick tool to rename and sort files that were generated by
    PaperPort MAX.  Files were separated by even and odd since
    it didnn't support duplex.  Also some odd or even pages were
    in reverse order.
    
    date 10/29/2008 
'''
import sys
import os
def debugArgv():
    print "Odd:"+oddPagePrefix + " R:" + str(oddPageIsReversed)
    print "Even:"+evenPagePrefix + " R: "+ str(evenPageIsReversed)
    print ("Out:"+outputPrefix)
    print ""
    print "Example: renamepng.py book_o 108 book_e_r 107 -r MyBook" 
def printHelp():
    print ("renamePNG sorts and renames png files in scanned documents")
    print ("")
    print ("renamepng.py [-t] [-i #] [-w #] [oddpage prefix] [last page#] <-r>  [even_prefix] [last page #]<-r> output_prefix")
    print ("-t: test run. No renaming")
    print ("-r: pages are in reverse order")
    print ("-i #: starting page #. -i 100 starts from page100")
    print "-w #: output digit width.  -w 3"
    print ""
    print "to skip odd pages: set last page# to 0 for Odd"
    print "    renamepng.py dummy 0 book_e_r 120 -r myBook"
    print ""
    print "to start from page 102 "
    print "renamepng.py -i 102 o 0 e_r 58 -r page"
    
    

def process(inPrefix,lastPage,inDigitWidth,outPrefix,isReversed,isEven,outDigitWidth,outputStartPage=1):
    currentPage=outputStartPage #start from page 1
    outputPage=outputStartPage
    #print "outputStartPage="+str(outputStartPage)
    #outputPage=1

    if isEven:
        evenOddFactor=0
    else: #ODD
        evenOddFactor=1
    #print "outDigitWidth="+str(outDigitWidth)
    if isReversed:
        currentPage=lastPage
        outputPage= (2*(lastPage-evenOddFactor) + outputPage)/2
        #outputPage = int((lastPage + outputPage)/2)
        print ("outputPage",outputPage)
        print ("last page",lastPage)
    if outDigitWidth <1:
        outDigitWidth=len(str(lastPage*2))
    pageCount=0
    while (pageCount < lastPage):
        in_filename=inPrefix+str(pageCount+1).zfill(inDigitWidth)+".png"
        #print "currentPage="+str(currentPage)
    
        out_filename =outPrefix +"_" + str(outputPage*2-evenOddFactor).zfill(outDigitWidth)+".png"
        print in_filename+ " ==> "+out_filename
    
        if not testRun:
            try:
                os.rename(in_filename,out_filename)
            except:
                print "ERROR: cannot rename "+in_filename
        if isReversed==True:
            currentPage=currentPage-1
            outputPage=outputPage-1
        else:
            currentPage=currentPage+1
            outputPage=outputPage+1
        pageCount=pageCount+1
        

if len(sys.argv) < 3 :
    printHelp()
    exit(0)
# Handle CMDLINE ARGV
argPos=1
testRun=False
startPage=1
oddPageIsReversed=False
evenPageIsReversed=False
outputDigitWidth=-1
if sys.argv[argPos]=="-t":
    testRun=True
    argPos=argPos+1
if sys.argv[argPos]=="-i" :
    startPage=int(sys.argv[argPos+1])
    argPos=argPos+2    
if sys.argv[argPos]=="-w" :
    outputDigitWidth=int(sys.argv[argPos+1])
    #print "outputDigitWidth set to "+str(outputDigitWidth)
    argPos=argPos+2    
    
oddPagePrefix=sys.argv[argPos]
argPos=argPos+1
oddLastPage=sys.argv[argPos]
argPos=argPos+1
if sys.argv[argPos]=="-r" :
    oddPageIsReversed=True
    argPos=argPos+1


evenPagePrefix=sys.argv[argPos]
argPos=argPos+1
evenLastPage=sys.argv[argPos]
argPos=argPos+1
if (sys.argv[argPos]=="-r"):
    evenPageIsReversed=True
    argPos=argPos+1
outputPrefix=sys.argv[argPos]
maxpage=max(int(oddLastPage),int(evenLastPage))
if outputDigitWidth <1 :
    outputDigitWidth=len(str(int(maxpage)*2))
#debugArgv()
print "outDigitWidht="+str(outputDigitWidth)
print "Odd:"+oddPagePrefix + "("+oddLastPage+ ") R:" + str(oddPageIsReversed)
print "Even:"+evenPagePrefix +  "("+ evenLastPage + ") R: "+ str(evenPageIsReversed)
print ("Out:"+outputPrefix)

# PROCESS FILES

#ODD PAGE
process(oddPagePrefix, int(oddLastPage),len(oddLastPage),outputPrefix,oddPageIsReversed,
    False,outputDigitWidth,startPage)

#even page
process(evenPagePrefix, int(evenLastPage),len(evenLastPage),outputPrefix,evenPageIsReversed,
    True,outputDigitWidth,startPage)

'''
currentPage=1 #start from page 1
#outputPage=1
if oddPageIsReversed:
    currentPage=oddLastPageNumber
#    outputPage=current
pageCount=0
while (pageCount < oddLastPageNumber):
    in_filename=oddPagePrefix+str(currentPage).zfill(len(oddLastPage))+".png"
    print "currentPage="+str(currentPage)
    out_filename =outputPrefix +"_"+str(currentPage*2-1)+".png"
    print in_filename+ " ==> "+out_filename

    #.zfill(oddLastPage)
    if oddPageIsReversed==True:
        currentPage=currentPage-1
    else:
        currentPage=currentPage+1
    pageCount=pageCount+1
'''


exit(0)

